# Generated by Django 5.2.17 on 2026-10-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_sequence_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted to an order'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='catalog.accession')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visitor_key', 'status'], name='holds_visitor_fa09ac_idx'), models.Index(fields=['status', 'expires_at'], name='holds_status_b50df8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('accession',), name='hold_one_active_per_piece'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(models.Q(('status', 'active'), _negated=True), ('ended_at__isnull', False)), _connector='OR'), name='hold_ended_at_matches_status')],
            },
        ),
    ]
