/*
  Every user-facing string lives here so tone can be reviewed in one place.
  Voice: dry, curious, confident. Light Swahili/Sheng where it falls naturally, never forced.
*/

export const copy = {
  brand: {
    name: "nboarchive",
    backRoom: "Back room",
  },

  errors: {
    network: "Could not reach the archive. Check your connection and try again.",
    unexpected: "Something in the back room slipped. Try again in a moment.",
    throttled: "Too many tries in a short time. Give it a few minutes.",
    sessionEnded: "Your session ended. Reload the page and sign in again.",
  },

  login: {
    eyebrow: "Staff only",
    title: "The back room",
    lede: "Drop your staff email. We send a one-time link, valid for 15 minutes. No passwords to forget.",
    emailLabel: "Staff email",
    emailHint: "The address the owner added you with.",
    submit: "Send my link",
    submitting: "Sending",
    sentTitle: "Check your inbox",
    sentBody: (email: string) =>
      `If ${email} is on the staff list, a link is on its way. It works once. Open it on this phone or any other.`,
    sentAgain: "Use a different email",
    expired: "Your session ran out. Sign in again to pick up where you left off.",
    invalidEmail: "That does not look like an email address.",
  },

  verify: {
    eyebrow: "One-time link",
    title: "Karibu ndani.",
    lede: "One tap and you are in. The link stops working after this.",
    submit: "Open the back room",
    submitting: "Opening",
    missingToken: "This link is missing its key. Request a fresh one.",
    invalid: "This link has been used or has expired. Links work once, for 15 minutes.",
    retry: "Try again",
    requestNew: "Request a new link",
  },

  desk: {
    eyebrow: "Back room",
    greeting: (name: string) => (name ? `Sasa, ${name.split(" ")[0]}.` : "Sasa."),
    signedInAs: "Signed in as",
    signOut: "Sign out",
    denied: "That room is for the owner. Ask them if you need in.",
    sectionsTitle: "Rooms",
    staffRoom: "Staff",
    staffRoomNote: "Who has keys, and what each key opens.",
    nothingYetTitle: "More rooms are being fitted",
    nothingYetBody: "Listing, drops and orders open here as each one is finished.",
  },

  staff: {
    eyebrow: "Back room / Staff",
    title: "Staff",
    add: "Add staff",
    addTitle: "Hand out a key",
    addLede: "They get a sign-in link by email straight away.",
    nameLabel: "Name",
    emailLabel: "Email",
    phoneLabel: "Phone (optional)",
    phoneHint: "Kenyan mobile, e.g. 0712 345 678.",
    roleLabel: "Role",
    create: "Add and send link",
    creating: "Adding",
    created: (email: string) => `${email} added. Their link is on its way.`,
    roleDescriptions: {
      owner: "Everything, including staff and money.",
      editor: "Lists items, runs drops.",
      packer: "Sees paid orders, packs and dispatches.",
    },
    columns: { person: "Person", role: "Role", lastSeen: "Last in" },
    neverSignedIn: "Not yet",
    you: "you",
    inactive: "Key returned",
    changeRole: "Change role",
    save: "Save",
    deactivate: "Take key back",
    reactivate: "Give key back",
    empty: "Only you so far. Add the people who help you list and pack.",
    count: (n: number) => (n === 1 ? "1 person" : `${n} people`),
    gone: "That person is no longer on the list. Reload to see the current staff.",
    roleRequired: "Pick a role.",
    saved: "Saved.",
    selfRoleLocked: "Another owner can change your role.",
    deactivateLabel: (name: string) => `Take key back from ${name}`,
    reactivateLabel: (name: string) => `Give key back to ${name}`,
    roleLabelFor: (name: string) => `Role for ${name}`,
    previous: "Previous page",
    next: "Next page",
  },

  nav: {
    label: "Index",
    latest: "Latest",
    archive: "Archive",
    drops: "Accessions",
    jumpLabel: "Jump to an archive number",
    jumpPlaceholder: "0142",
    jumpSubmit: "Go",
  },

  colophon: {
    statement:
      "Thrifted polos, jackets, sweaters, hoodies and tees. Every piece numbered, measured flat, cleaned and inspected before it is filed. Catalogued in Nairobi.",
    set: "Set in Bricolage Grotesque, Instrument Sans and DM Mono.",
    staff: "Staff",
  },

  labels: {
    category: {
      polo: "Polo",
      jacket: "Jacket",
      sweater: "Sweater",
      hoodie: "Hoodie",
      tee: "Tee",
    },
    categoryPlural: {
      polo: "Polos",
      jacket: "Jackets",
      sweater: "Sweaters",
      hoodie: "Hoodies",
      tee: "Tees",
    },
    condition: {
      mint: "Mint",
      excellent: "Excellent",
      good: "Good",
      worn_in: "Worn-in",
    },
    chestBand: { xs: "XS", s: "S", m: "M", l: "L", xl: "XL", xxl: "XXL" },
    imageKind: {
      front: "Front",
      back: "Back",
      tag: "Brand tag",
      care: "Care label",
      texture: "Fabric",
      flaw: "Flaw close-up",
      on_body: "On body",
    },
    measurement: {
      chest: "Chest, pit to pit",
      length: "Length, collar to hem",
      shoulder: "Shoulder, seam to seam",
      sleeve: "Sleeve",
    },
    extras: {
      collar_condition: "Collar",
      placket_condition: "Placket",
      knit_type: "Knit",
      jacket_type: "Type",
      closure_condition: "Closure",
      lining_condition: "Lining",
      insulation: "Insulation",
      fibre: "Fibre",
      pilling_level: "Pilling",
      neckline: "Neckline",
      style: "Style",
      hood_condition: "Hood",
      print_condition: "Print",
      fleece_weight: "Fleece",
      graphic: "Front",
      stitch: "Stitch",
    } as Record<string, string>,
  },

  piece: {
    sample: "Sample piece",
    sampleNote:
      "A sample record, filed while the archive is being set up. It is not for sale and will be removed before launch.",
    noPhoto: "Photo to come",
    priceToCome: "Price to come",
    held: "On hold",
    claimed: "Claimed",
  },

  home: {
    eyebrow: "Latest accession",
    filed: (date: string) => `Filed ${date}`,
    open: "Open the record",
    recentTitle: "Filed before it",
    browse: "The whole archive",
    emptyTitle: "Nothing filed yet.",
    emptyBody: "The first pieces are being measured and photographed. Check back soon.",
  },

  archive: {
    eyebrow: "Archive",
    title: "The archive",
    count: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
    filters: "Filters",
    filtersCount: (n: number) => `Filters (${n})`,
    filtersTitle: "Narrow the archive",
    filtersDescription: "Pick as many as you like. Sizes go by the chest measurement, not the tag.",
    category: "Category",
    size: "Size (by chest)",
    condition: "Condition",
    era: "Era",
    brand: "Brand",
    colour: "Colour",
    drop: "Accession",
    anyDrop: "Any",
    price: "Price (KES)",
    priceMin: "From",
    priceMax: "To",
    showClaimed: "Show claimed pieces too",
    apply: "Show pieces",
    clear: "Clear all",
    remove: (label: string) => `Remove filter: ${label}`,
    sortLabel: "Order",
    sort: {
      newest: "Newest",
      price: "Price, low first",
      "-price": "Price, high first",
      number: "Oldest number",
      "-number": "Newest number",
    },
    emptyTitle: "Nothing under those filters.",
    emptyBody: "Loosen one or two and the shelf fills back up.",
    page: (page: number, pages: number) => `Page ${page} of ${pages}`,
    previous: "Previous page",
    next: "Next page",
  },

  item: {
    eyebrow: "Accession record",
    label: "Label",
    brand: "Brand",
    taggedSize: "Tagged size",
    fitsLike: (band: string) => `fits like ${band} by chest`,
    colour: "Colour",
    fabric: "Fabric",
    era: "Era",
    condition: "Condition",
    cleaned: "Cleaned and inspected",
    drop: "Accession",
    fit: "Fit",
    measurementsTitle: "Measurements",
    measurementsCaption: "Measured flat, in centimetres. Lay a top you own flat and compare.",
    flawsTitle: "Flaws",
    flawsLede:
      "Everything we found, photographed close up. If it is not listed, we did not see it.",
    noFlaws: "None found on inspection.",
    provenanceTitle: "Where it came from",
    photosTitle: "Photographs",
    relatedTitle: "Same era",
    onRail: "On the rail",
    holdsSoon:
      "Holds open soon: one tap reserves a piece for 15 minutes while you pay. Until then this one waits here.",
    heldNote:
      "Someone is paying for this right now. If they let it go, it comes back within 15 minutes.",
    claimedNote: (city: string, date: string) =>
      city
        ? `Went to ${city} on ${date}. The record stays.`
        : `Claimed on ${date}. The record stays.`,
    claimedNoteUndated: "Claimed. The record stays.",
  },

  drops: {
    eyebrow: "Accessions",
    title: "Accessions",
    lede: "Pieces are filed in numbered batches. Each accession opens at a set time; until then you can only see that it is coming.",
    number: (n: number) => `Accession ${String(n).padStart(2, "0")}`,
    pieces: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
    released: (date: string) => `Opened ${date}`,
    opensAt: (date: string) => `Opens ${date}`,
    opensIn: "Opens in",
    countdownUnits: { days: "days", hours: "hrs", minutes: "min", seconds: "sec" },
    opening: "Opening now",
    unscheduled: "Date to come",
    view: "View accession",
    sealedTitle: (n: number) =>
      n === 1 ? "1 piece is filed for this release." : `${n} pieces are filed for this release.`,
    sealedBody: "They stay in the drawer until it opens. Come back at the time above.",
    emptyTitle: "No accessions yet.",
    emptyBody: "The first numbered release is being put together.",
    emptyReleased: "Every piece in this accession is filed under the archive now.",
    next: "Next accession",
  },

  system: {
    notFoundEyebrow: "Not in the index",
    notFoundTitle: "No accession under that number.",
    notFoundBody: "Either it never existed or someone filed it somewhere strange.",
    notFoundBack: "Back to the archive",
    errorEyebrow: "Misfiled",
    errorTitle: "Something went wrong on our side.",
    errorBody: "It is not you. Try again; if it keeps happening, the team will see it.",
    retry: "Try again",
  },
} as const;
