/*
  Every user-facing string lives here so tone can be reviewed in one place.
  Voice: dry, curious, confident. Light Swahili/Sheng where it falls naturally, never forced.
*/

export const copy = {
  brand: {
    name: "nboarchive",
    backRoom: "Back room",
  },

  errors: {
    network: "Could not reach the archive. Check your connection and try again.",
    unexpected: "Something in the back room slipped. Try again in a moment.",
    throttled: "Too many tries in a short time. Give it a few minutes.",
    sessionEnded: "Your session ended. Reload the page and sign in again.",
  },

  login: {
    eyebrow: "Staff only",
    title: "The back room",
    lede: "Drop your staff email. We send a one-time link, valid for 15 minutes. No passwords to forget.",
    emailLabel: "Staff email",
    emailHint: "The address the owner added you with.",
    submit: "Send my link",
    submitting: "Sending",
    sentTitle: "Check your inbox",
    sentBody: (email: string) =>
      `If ${email} is on the staff list, a link is on its way. It works once. Open it on this phone or any other.`,
    sentAgain: "Use a different email",
    expired: "Your session ran out. Sign in again to pick up where you left off.",
    invalidEmail: "That does not look like an email address.",
  },

  verify: {
    eyebrow: "One-time link",
    title: "Karibu ndani.",
    lede: "One tap and you are in. The link stops working after this.",
    submit: "Open the back room",
    submitting: "Opening",
    missingToken: "This link is missing its key. Request a fresh one.",
    invalid: "This link has been used or has expired. Links work once, for 15 minutes.",
    retry: "Try again",
    requestNew: "Request a new link",
  },

  desk: {
    eyebrow: "Back room",
    greeting: (name: string) => (name ? `Sasa, ${name.split(" ")[0]}.` : "Sasa."),
    signedInAs: "Signed in as",
    signOut: "Sign out",
    denied: "Your key does not open that room. Ask the owner if you need in.",
    sectionsTitle: "Rooms",
    staffRoom: "Staff",
    staffRoomNote: "Who has keys, and what each key opens.",
    nothingYetTitle: "More rooms are being fitted",
    nothingYetBody: "Quick listing and orders open here as each one is finished.",
    accessionsRoom: "Accessions",
    accessionsRoomNote: "File, photograph, price and publish pieces.",
    dropsRoom: "Drops",
    dropsRoomNote: "Numbered releases and when they open.",
  },

  staff: {
    eyebrow: "Back room / Staff",
    title: "Staff",
    add: "Add staff",
    addTitle: "Hand out a key",
    addLede: "They get a sign-in link by email straight away.",
    nameLabel: "Name",
    emailLabel: "Email",
    phoneLabel: "Phone (optional)",
    phoneHint: "Kenyan mobile, e.g. 0712 345 678.",
    roleLabel: "Role",
    create: "Add and send link",
    creating: "Adding",
    created: (email: string) => `${email} added. Their link is on its way.`,
    roleDescriptions: {
      owner: "Everything, including staff and money.",
      editor: "Lists items, runs drops.",
      packer: "Sees paid orders, packs and dispatches.",
    },
    columns: { person: "Person", role: "Role", lastSeen: "Last in" },
    neverSignedIn: "Not yet",
    you: "you",
    inactive: "Key returned",
    changeRole: "Change role",
    save: "Save",
    deactivate: "Take key back",
    reactivate: "Give key back",
    empty: "Only you so far. Add the people who help you list and pack.",
    count: (n: number) => (n === 1 ? "1 person" : `${n} people`),
    gone: "That person is no longer on the list. Reload to see the current staff.",
    roleRequired: "Pick a role.",
    saved: "Saved.",
    selfRoleLocked: "Another owner can change your role.",
    deactivateLabel: (name: string) => `Take key back from ${name}`,
    reactivateLabel: (name: string) => `Give key back to ${name}`,
    roleLabelFor: (name: string) => `Role for ${name}`,
    previous: "Previous page",
    next: "Next page",
  },

  nav: {
    label: "Index",
    latest: "Latest",
    archive: "Archive",
    drops: "Accessions",
    jumpLabel: "Jump to an archive number",
    jumpPlaceholder: "0142",
    jumpSubmit: "Go",
  },

  colophon: {
    statement:
      "Thrifted polos, jackets, sweaters, hoodies and tees. Every piece numbered, measured flat, cleaned and inspected before it is filed. Catalogued in Nairobi.",
    set: "Set in Bricolage Grotesque, Instrument Sans and DM Mono.",
    staff: "Staff",
  },

  labels: {
    category: {
      polo: "Polo",
      jacket: "Jacket",
      sweater: "Sweater",
      hoodie: "Hoodie",
      tee: "Tee",
    },
    categoryPlural: {
      polo: "Polos",
      jacket: "Jackets",
      sweater: "Sweaters",
      hoodie: "Hoodies",
      tee: "Tees",
    },
    condition: {
      mint: "Mint",
      excellent: "Excellent",
      good: "Good",
      worn_in: "Worn-in",
    },
    chestBand: { xs: "XS", s: "S", m: "M", l: "L", xl: "XL", xxl: "XXL" },
    imageKind: {
      front: "Front",
      back: "Back",
      tag: "Brand tag",
      care: "Care label",
      texture: "Fabric",
      flaw: "Flaw close-up",
      on_body: "On body",
    },
    measurement: {
      chest: "Chest, pit to pit",
      length: "Length, collar to hem",
      shoulder: "Shoulder, seam to seam",
      sleeve: "Sleeve",
    },
    extras: {
      collar_condition: "Collar",
      placket_condition: "Placket",
      knit_type: "Knit",
      jacket_type: "Type",
      closure_condition: "Closure",
      lining_condition: "Lining",
      insulation: "Insulation",
      fibre: "Fibre",
      pilling_level: "Pilling",
      neckline: "Neckline",
      style: "Style",
      hood_condition: "Hood",
      print_condition: "Print",
      fleece_weight: "Fleece",
      graphic: "Front",
      stitch: "Stitch",
    } as Record<string, string>,
  },

  piece: {
    sample: "Sample piece",
    sampleNote:
      "A sample record, filed while the archive is being set up. It is not for sale and will be removed before launch.",
    noPhoto: "Photo to come",
    priceToCome: "Price to come",
    held: "On hold",
    claimed: "Claimed",
  },

  home: {
    eyebrow: "Latest accession",
    filed: (date: string) => `Filed ${date}`,
    open: "Open the record",
    recentTitle: "Filed before it",
    browse: "The whole archive",
    emptyTitle: "Nothing filed yet.",
    emptyBody: "The first pieces are being measured and photographed. Check back soon.",
  },

  archive: {
    eyebrow: "Archive",
    title: "The archive",
    count: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
    filters: "Filters",
    filtersCount: (n: number) => `Filters (${n})`,
    filtersTitle: "Narrow the archive",
    filtersDescription: "Pick as many as you like. Sizes go by the chest measurement, not the tag.",
    category: "Category",
    size: "Size (by chest)",
    condition: "Condition",
    era: "Era",
    brand: "Brand",
    colour: "Colour",
    drop: "Accession",
    anyDrop: "Any",
    price: "Price (KES)",
    priceMin: "From",
    priceMax: "To",
    showClaimed: "Show claimed pieces too",
    apply: "Show pieces",
    clear: "Clear all",
    remove: (label: string) => `Remove filter: ${label}`,
    sortLabel: "Order",
    sort: {
      newest: "Newest",
      price: "Price, low first",
      "-price": "Price, high first",
      number: "Oldest number",
      "-number": "Newest number",
    },
    emptyTitle: "Nothing under those filters.",
    emptyBody: "Loosen one or two and the shelf fills back up.",
    page: (page: number, pages: number) => `Page ${page} of ${pages}`,
    previous: "Previous page",
    next: "Next page",
  },

  item: {
    eyebrow: "Accession record",
    label: "Label",
    brand: "Brand",
    taggedSize: "Tagged size",
    fitsLike: (band: string) => `fits like ${band} by chest`,
    colour: "Colour",
    fabric: "Fabric",
    era: "Era",
    condition: "Condition",
    cleaned: "Cleaned and inspected",
    drop: "Accession",
    fit: "Fit",
    measurementsTitle: "Measurements",
    measurementsCaption: "Measured flat, in centimetres. Lay a top you own flat and compare.",
    flawsTitle: "Flaws",
    flawsLede:
      "Everything we found, photographed close up. If it is not listed, we did not see it.",
    noFlaws: "None found on inspection.",
    provenanceTitle: "Where it came from",
    photosTitle: "Photographs",
    relatedTitle: "Same era",
    onRail: "On the rail",
    holdsSoon:
      "Holds open soon: one tap reserves a piece for 15 minutes while you pay. Until then this one waits here.",
    heldNote:
      "Someone is paying for this right now. If they let it go, it comes back within 15 minutes.",
    claimedNote: (city: string, date: string) =>
      city
        ? `Went to ${city} on ${date}. The record stays.`
        : `Claimed on ${date}. The record stays.`,
    claimedNoteUndated: "Claimed. The record stays.",
  },

  drops: {
    eyebrow: "Accessions",
    title: "Accessions",
    lede: "Pieces are filed in numbered batches. Each accession opens at a set time; until then you can only see that it is coming.",
    number: (n: number) => `Accession ${String(n).padStart(2, "0")}`,
    pieces: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
    released: (date: string) => `Opened ${date}`,
    opensAt: (date: string) => `Opens ${date}`,
    opensIn: "Opens in",
    countdownUnits: { days: "days", hours: "hrs", minutes: "min", seconds: "sec" },
    opening: "Opening now",
    unscheduled: "Date to come",
    view: "View accession",
    sealedTitle: (n: number) =>
      n === 1 ? "1 piece is filed for this release." : `${n} pieces are filed for this release.`,
    sealedBody: "They stay in the drawer until it opens. Come back at the time above.",
    emptyTitle: "No accessions yet.",
    emptyBody: "The first numbered release is being put together.",
    emptyReleased: "Every piece in this accession is filed under the archive now.",
    next: "Next accession",
  },

  hold: {
    place: "Place on hold",
    placing: "Holding",
    placeNote:
      "One tap keeps it for you for 15 minutes while you pay. Nobody else can take it in that time.",
    yours: "Held for you",
    yoursNote: "It is yours for the time on the clock. Let it go if you change your mind.",
    timerLabel: "Time left on your hold",
    expiredNote: "Your time ran out and the piece went back on the rail.",
    release: "Let it go",
    releasing: "Letting go",
    released: "Let go. It is back on the rail.",
    seeHolds: "Your holds",
    backIn: (minutes: number) =>
      minutes <= 1
        ? "Someone is paying for this right now. If they let it go, it comes back within a minute."
        : `Someone is paying for this right now. If they let it go, it comes back in about ${minutes} minutes.`,
    errors: {
      pieceHeld:
        "Someone got to it a moment before you. If they let it go, it comes back within 15 minutes.",
      notForSale: "This piece is no longer for sale.",
      limit: (max: number) =>
        `You are already holding ${max} pieces, the most at once. Let one go to hold this one.`,
      closed: "Holds are not open yet.",
      gone: "That piece is no longer in the archive.",
    },
    page: {
      eyebrow: "Holds",
      title: "On hold for you",
      count: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
      emptyTitle: "Nothing on hold.",
      emptyBody:
        "Find something in the archive and tap Place on hold. It keeps the piece for you for 15 minutes.",
      browse: "Back to the archive",
      checkoutSoon:
        "Paying online opens in the next update. Until then a hold keeps a piece off the rail for the time on its clock.",
      open: "Open the record",
    },
    nav: (n: number) => `On hold (${n})`,
  },

  pieceStatus: {
    draft: "Draft",
    scheduled: "Scheduled",
    live: "Live",
    held: "Held",
    claimed: "Claimed",
    withdrawn: "Withdrawn",
  },

  accessionsDesk: {
    eyebrow: "Back room / Accessions",
    title: "Accessions",
    newPiece: "New piece",
    newTitle: "Start a record",
    newLede: "Pick what it is. It takes the next archive number now; the rest can wait.",
    categoryLabel: "Category",
    categoryRequired: "Pick a category.",
    create: "Take a number",
    creating: "Filing",
    statusLabel: "Status",
    anyStatus: "Any status",
    anyCategory: "Any category",
    searchLabel: "Search",
    searchHint: "Title, brand or archive number.",
    apply: "Filter",
    clear: "Clear",
    columns: { piece: "Piece", status: "Status", price: "Price", updated: "Last touched" },
    empty: "Nothing filed yet. Start with New piece.",
    emptyFiltered: "No pieces match. Clear the filters to see everything.",
    count: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
    photos: (n: number) => (n === 1 ? "1 photo" : `${n} photos`),
    untitled: "Untitled draft",
    sample: "Sample",
    noPrice: "No price",
    previous: "Previous page",
    next: "Next page",
    gone: "That piece is no longer on file. Reload the list.",
  },

  pieceDesk: {
    back: "All accessions",
    viewOnSite: "View on site",
    createdBy: (email: string) => `Filed by ${email}`,
    releaseAt: (when: string) => `Goes out ${when}`,
    publishedAt: (when: string) => `Out since ${when}`,
    readOnly: "You can look; owners and editors make changes.",
    locked: (status: string) =>
      `This piece is ${status.toLowerCase()}. A sale is in progress or done, so the record stays as it is.`,
    sampleNote: "Sample record. Run purge_placeholders before launch to clear it.",
    problemsTitle: "Before it can go out",
    problemsReady: "Complete. Ready to publish.",
    problemField: {
      title: "Title",
      brand: "Brand",
      tagged_size: "Tagged size",
      colour: "Colour",
      fabric_composition: "Fabric",
      condition_grade: "Condition",
      price_kes: "Price",
      cleaned_at: "Cleaned date",
      measurements: "Measurements",
      images: "Photos",
      flaws: "Flaws",
    } as Record<string, string>,
    notReady: "Not ready yet. The list above says what is missing.",
    publish: "Publish now",
    published: "Live on the archive.",
    schedule: "Schedule",
    scheduleTitle: "Schedule this piece",
    scheduleLede: "It stays off the storefront until the release time, then goes out on its own.",
    scheduleInDrop: (number: string) =>
      `It goes out with Accession ${number} at the drop's release time.`,
    releaseAtLabel: "Release time (Nairobi)",
    releaseAtHint: "Day and time in Nairobi, whatever your phone's clock says.",
    releaseAtInvalid: "Pick a real date and time.",
    scheduleConfirm: "Schedule it",
    scheduled: (when: string) => `Scheduled for ${when}.`,
    withdraw: "Withdraw",
    withdrawTitle: "Take this piece off the archive?",
    withdrawBody: "It leaves the storefront straight away. You can publish it again later.",
    withdrawn: "Withdrawn. It is off the storefront.",
    heldUntil: (when: string) => `On hold until ${when}`,
    releaseHold: "Release hold",
    releaseHoldTitle: "Put this piece back on the rail?",
    releaseHoldBody:
      "The visitor holding it loses their hold now, before their clock runs out. Use this for a stuck hold.",
    holdReleased: "Hold released. It is back on the rail.",
    deleteDraft: "Delete draft",
    deleteTitle: "Delete this draft?",
    deleteBody: (archiveNo: string) =>
      `The record and its photos go. ${archiveNo} is not handed out again.`,
    sections: {
      label: "Label",
      measurements: "Measurements",
      measurementsLede: "Laid flat, in whole centimetres.",
      extras: "Category details",
      drop: "Drop",
      photos: "Photos",
      flaws: "Flaws",
      flawsLede: "Every flaw gets its own close-up. Upload it as a Flaw photo first.",
    },
    fields: {
      title: "Title",
      category: "Category",
      categoryHint: "Changing the category clears the category details.",
      brand: "Brand / label",
      taggedSize: "Tagged size",
      fitNote: "Fit note",
      fitNoteHint: "e.g. oversized, boxy, slim.",
      colour: "Colour",
      fabric: "Fabric (from the care label)",
      era: "Era or year (optional)",
      condition: "Condition",
      notSet: "Not set",
      cleanedAt: "Cleaned and inspected on",
      price: "Price (KES)",
      priceInvalid: "Whole shillings, 1 or more.",
      provenance: "Provenance note",
      dateInvalid: "Pick a real date.",
      tooLong: "That is too long for this field.",
    },
    notRecorded: "Not recorded",
    dropLabel: "Drop",
    noDrop: "Not in a drop",
    dropHint: "A piece in a drop goes out at the drop's release time.",
    dropOption: (number: string, title: string, status?: string) =>
      `Accession ${number}: ${title}${status ? ` (${status.toLowerCase()})` : ""}`,
    save: "Save",
    saving: "Saving",
    saved: "Saved.",
  },

  photosDesk: {
    add: "Add photos",
    kindLabel: "Kind",
    fileLabel: "Photos",
    hint: "JPEG, PNG or WebP, up to 15 MB each. Twelve photos at most.",
    full: "This piece has all twelve photos.",
    none: "No photos yet. Front, back and the brand tag first.",
    uploading: (done: number, total: number) => `Uploading ${done + 1} of ${total}`,
    uploaded: (n: number) => (n === 1 ? "1 photo added." : `${n} photos added.`),
    failed: (name: string, reason: string) => `${name}: ${reason}`,
    pickFiles: "Choose at least one photo.",
    tooBig: "Over 15 MB. Export a smaller copy.",
    tooMany: (left: number) =>
      left === 0 ? "No room for more photos." : `Only ${left} more fit on this piece.`,
    altLabel: "Alt text",
    altHint: "What the photo shows, for screen readers.",
    moveUp: "Move earlier",
    moveDown: "Move later",
    remove: "Remove",
    removeTitle: "Remove this photo?",
    removeBody: "The file is deleted. A flaw using it loses its close-up.",
    position: (n: number) => `Photo ${n}`,
  },

  flawsDesk: {
    descriptionLabel: "What and where",
    descriptionHint: "e.g. Small mark inside the left cuff.",
    photoLabel: "Close-up",
    noPhoto: "No photo yet",
    add: "List flaw",
    none: "No flaws listed.",
    remove: "Remove",
    removeTitle: "Remove this flaw?",
    removeBody: "Only if it was listed by mistake or has been repaired.",
    required: "Describe the flaw.",
    number: (n: number) => `Flaw ${n}`,
  },

  dropsDesk: {
    eyebrow: "Back room / Drops",
    title: "Drops",
    newDrop: "New drop",
    newTitle: "Open a drop",
    newLede: "It takes the next drop number. Set the release time once its pieces are in.",
    titleLabel: "Title",
    titleRequired: "Give it a title.",
    introLabel: "Intro",
    introHint: "The cataloguing note shown above the drop.",
    create: "Open drop",
    creating: "Opening",
    status: { draft: "Draft", scheduled: "Scheduled", released: "Released" },
    columns: { drop: "Drop", status: "Status", release: "Release", pieces: "Pieces" },
    pieces: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
    noRelease: "Not set",
    edit: "Edit",
    editTitle: (number: string) => `Accession ${number}`,
    details: "Details",
    save: "Save",
    saved: "Saved.",
    scheduleLabel: "Release time (Nairobi)",
    scheduleHint: "Scheduled pieces in this drop move with it.",
    schedule: "Set release time",
    scheduled: (when: string) => `Releases ${when}.`,
    release: "Release now",
    releaseTitle: (number: string) => `Release Accession ${number} now?`,
    releaseBody: "Every piece scheduled into it goes live at once.",
    released: "Released. Its pieces are live.",
    delete: "Delete",
    deleteTitle: (number: string) => `Delete Accession ${number}?`,
    deleteBody: "Only drafts can be deleted. Pieces in it stay on file and leave the drop.",
    empty: "No drops yet. Open one when a batch is ready.",
    count: (n: number) => (n === 1 ? "1 drop" : `${n} drops`),
    gone: "That drop is no longer on file. Reload the list.",
    previous: "Previous page",
    next: "Next page",
  },

  system: {
    notFoundEyebrow: "Not in the index",
    notFoundTitle: "No accession under that number.",
    notFoundBody: "Either it never existed or someone filed it somewhere strange.",
    notFoundBack: "Back to the archive",
    errorEyebrow: "Misfiled",
    errorTitle: "Something went wrong on our side.",
    errorBody: "It is not you. Try again; if it keeps happening, the team will see it.",
    retry: "Try again",
  },
} as const;
