# Generated by Django 5.2.17 on 2026-10-07 19:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropAlertSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('consented_at', models.DateTimeField()),
                ('consent_version', models.CharField(max_length=20)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drop_alert_subscribers',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('phone', ''), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='drop_alert_has_contact'), models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='drop_alert_phone_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='drop_alert_email_unique')],
            },
        ),
    ]
