# Generated by Django 5.2.17 on 2026-10-06 20:33

import apps.catalog.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sequences',
            },
        ),
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('polo', 'Polo shirts'), ('jacket', 'Jackets'), ('sweater', 'Sweaters'), ('hoodie', 'Hoodies'), ('tee', 'T-shirts')], max_length=16)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('tagged_size', models.CharField(blank=True, max_length=24)),
                ('fit_note', models.CharField(blank=True, max_length=120)),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('fabric_composition', models.CharField(blank=True, max_length=160)),
                ('era', models.CharField(blank=True, max_length=40)),
                ('condition_grade', models.CharField(blank=True, choices=[('mint', 'Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('worn_in', 'Worn-in')], max_length=16)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('chest_band', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=8)),
                ('category_extras', models.JSONField(blank=True, default=dict)),
                ('cleaned_at', models.DateField(blank=True, null=True)),
                ('provenance_note', models.TextField(blank=True, max_length=600)),
                ('price_kes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('held', 'Held'), ('claimed', 'Claimed'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_city', models.CharField(blank=True, max_length=60)),
                ('is_placeholder', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accessions',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='AccessionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('tag', 'Brand tag'), ('care', 'Care label'), ('texture', 'Fabric texture'), ('flaw', 'Flaw close-up'), ('on_body', 'On body')], max_length=16)),
                ('file', models.ImageField(height_field='height', upload_to=apps.catalog.models._image_path, width_field='width')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('placeholder', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.accession')),
            ],
            options={
                'db_table': 'accession_images',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('intro', models.TextField(blank=True)),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('released', 'Released')], default='draft', max_length=16)),
            ],
            options={
                'db_table': 'drops',
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['status', 'release_at'], name='drops_status_885498_idx')],
            },
        ),
        migrations.AddField(
            model_name='accession',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessions', to='catalog.drop'),
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=280)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaws', to='catalog.accession')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flaws', to='catalog.accessionimage')),
            ],
            options={
                'db_table': 'flaws',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['status', 'published_at'], name='accessions_status_d091fc_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['status', 'release_at'], name='accessions_status_98e2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['category', 'status'], name='accessions_categor_13a28b_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['chest_band'], name='accessions_chest_b_55c157_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['price_kes'], name='accessions_price_k_3626b9_idx'),
        ),
        migrations.AddIndex(
            model_name='accession',
            index=models.Index(fields=['era'], name='accessions_era_7e5bd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='accession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'scheduled'), _negated=True), ('release_at__isnull', False), _connector='OR'), name='accession_scheduled_has_release_at'),
        ),
    ]
